In [114]:
#importing modules
import pandas as pd
import numpy as np
import matplotlib.pyplot as plt

#downloading file
df = pd.read_csv('C:/Users/yurin/desktop/noshowappointments-kagglev2-may-2016.csv')
df

,PatientId,AppointmentID,Gender,ScheduledDay,AppointmentDay,Age,Neighbourhood,Scholarship,Hipertension,Diabetes,Alcoholism,Handcap,SMS_received,No-show
0,2.987250e+13,5642903,F,2016-04-29T18:38:08Z,2016-04-29T00:00:00Z,62,JARDIM DA PENHA,0,1,0,0,0,0,No
1,5.589978e+14,5642503,M,2016-04-29T16:08:27Z,2016-04-29T00:00:00Z,56,JARDIM DA PENHA,0,0,0,0,0,0,No
2,4.262962e+12,5642549,F,2016-04-29T16:19:04Z,2016-04-29T00:00:00Z,62,MATA DA PRAIA,0,0,0,0,0,0,No
3,8.679512e+11,5642828,F,2016-04-29T17:29:31Z,2016-04-29T00:00:00Z,8,PONTAL DE CAMBURI,0,0,0,0,0,0,No
4,8.841186e+12,5642494,F,2016-04-29T16:07:23Z,2016-04-29T00:00:00Z,56,JARDIM DA PENHA,0,1,1,0,0,0,No
5,9.598513e+13,5626772,F,2016-04-27T08:36:51Z,2016-04-29T00:00:00Z,76,REPÃšBLICA,0,1,0,0,0,0,No
6,7.336882e+14,5630279,F,2016-04-27T15:05:12Z,2016-04-29T00:00:00Z,23,GOIABEIRAS,0,0,0,0,0,0,Yes
7,3.449833e+12,5630575,F,2016-04-27T15:39:58Z,2016-04-29T00:00:00Z,39,GOIABEIRAS,0,0,0,0,0,0,Yes
8,5.639473e+13,5638447,F,2016-04-29T08:02:16Z,2016-04-29T00:00:00Z,21,ANDORINHAS,0,0,0,0,0,0,No
9,7.812456e+13,5629123,F,2016-04-27T12:48:25Z,2016-04-29T00:00:00Z,19,CONQUISTA,0,0,0,0,0,0,No
10,7.345362e+14,5630213,F,2016-04-27T14:58:11Z,2016-04-29T00:00:00Z,30,NOVA PALESTINA,0,0,0,0,0,0,No
11,7.542951e+12,5620163,M,2016-04-26T08:44:12Z,2016-04-29T00:00:00Z,29,NOVA PALESTINA,0,0,0,0,0,1,Yes
12,5.666548e+14,5634718,F,2016-04-28T11:33:51Z,2016-04-29T00:00:00Z,22,NOVA PALESTINA,1,0,0,0,0,0,No
13,9.113946e+14,5636249,M,2016-04-28T14:52:07Z,2016-04-29T00:00:00Z,28,NOVA PALESTINA,0,0,0,0,0,0,No
14,9.988472e+13,5633951,F,2016-04-28T10:06:24Z,2016-04-29T00:00:00Z,54,NOVA PALESTINA,0,0,0,0,0,0,No
15,9.994839e+10,5620206,F,2016-04-26T08:47:27Z,2016-04-29T00:00:00Z,15,NOVA PALESTINA,0,0,0,0,0,1,No
16,8.457439e+13,5633121,M,2016-04-28T08:51:47Z,2016-04-29T00:00:00Z,50,NOVA PALESTINA,0,0,0,0,0,0,No
17,1.479497e+13,5633460,F,2016-04-28T09:28:57Z,2016-04-29T00:00:00Z,40,CONQUISTA,1,0,0,0,0,0,Yes
18,1.713538e+13,5621836,F,2016-04-26T10:54:18Z,2016-04-29T00:00:00Z,30,NOVA PALESTINA,1,0,0,0,0,1,No
19,7.223289e+12,5640433,F,2016-04-29T10:43:14Z,2016-04-29T00:00:00Z,46,DA PENHA,0,0,0,0,0,0,No
20,6.222575e+14,5626083,F,2016-04-27T07:51:14Z,2016-04-29T00:00:00Z,30,NOVA PALESTINA,0,0,0,0,0,0,Yes
21,1.215484e+13,5628338,F,2016-04-27T10:50:45Z,2016-04-29T00:00:00Z,4,CONQUISTA,0,0,0,0,0,0,Yes
22,8.632298e+14,5616091,M,2016-04-25T13:29:16Z,2016-04-29T00:00:00Z,13,CONQUISTA,0,0,0,0,0,1,Yes
23,2.137540e+14,5634142,F,2016-04-28T10:27:05Z,2016-04-29T00:00:00Z,46,CONQUISTA,0,0,0,0,0,0,No
24,8.734858e+12,5641780,F,2016-04-29T14:19:19Z,2016-04-29T00:00:00Z,65,TABUAZEIRO,0,0,0,0,0,0,No
25,5.819370e+12,5624020,M,2016-04-26T15:04:17Z,2016-04-29T00:00:00Z,46,CONQUISTA,0,1,0,0,0,1,No
26,2.578785e+10,5641781,F,2016-04-29T14:19:42Z,2016-04-29T00:00:00Z,45,BENTO FERREIRA,0,1,0,0,0,0,No
27,1.215484e+13,5628345,F,2016-04-27T10:51:45Z,2016-04-29T00:00:00Z,4,CONQUISTA,0,0,0,0,0,0,No
28,5.926172e+12,5642400,M,2016-04-29T15:48:02Z,2016-04-29T00:00:00Z,51,SÃƒO PEDRO,0,0,0,0,0,0,No
29,1.225776e+12,5642186,F,2016-04-29T15:16:29Z,2016-04-29T00:00:00Z,32,SANTA MARTHA,0,0,0,0,0,0,No
...,...,...,...,...,...,...,...,...,...,...,...,...,...,...
110497,7.935892e+14,5757745,M,2016-06-01T09:46:33Z,2016-06-01T00:00:00Z,76,MARIA ORTIZ,0,0,0,0,0,0,No
110498,9.433654e+13,5787655,F,2016-06-08T10:21:14Z,2016-06-08T00:00:00Z,59,MARIA ORTIZ,0,0,0,0,0,0,No
110499,8.219692e+14,5757697,F,2016-06-01T09:42:56Z,2016-06-01T00:00:00Z,66,MARIA ORTIZ,0,1,1,0,0,0,No
110500,4.434384e+14,5787233,F,2016-06-08T09:35:13Z,2016-06-08T00:00:00Z,59,MARIA ORTIZ,0,0,0,0,0,0,No
110501,4.544252e+11,5758133,M,2016-06-01T10:19:12Z,2016-06-01T00:00:00Z,44,MARIA ORTIZ,0,0,0,0,0,0,No
110502,7.316229e+14,5787937,F,2016-06-08T10:50:42Z,2016-06-08T00:00:00Z,22,GOIABEIRAS,0,0,0,0,0,0,No
110503,2.362182e+13,5759473,F,2016-06-01T13:00:36Z,2016-06-01T00:00:00Z,64,SOLON BORGES,0,0,0,0,0,0,No
110504,9.947983e+12,5788052,F,2016-06-08T11:06:21Z,2016-06-08T00:00:00Z,4,MARIA ORTIZ,0,0,0,0,0,0,No
110505,5.667344e+13,5758455,F,2016-06-01T10:45:50Z,2016-06-01T00:00:00Z,55,MARIA ORTIZ,0,0,0,0,0,0,No
110506,8.973883e+11,5758779,M,2016-06-01T11:09:20Z,2016-06-01T00:00:00Z,5,MARIA ORTIZ,0,0,0,0,0,0,No
110507,4.769462e+14,5786918,F,2016-06-08T09:04:18Z,2016-06-08T00:00:00Z,0,MARIA ORTIZ,0,0,0,0,0,0,No
110508,9.433654e+13,5757656,F,2016-06-01T09:41:00Z,2016-06-01T00:00:00Z,59,MARIA ORTIZ,0,0,0,0,0,0,No
110509,4.952968e+14,5786750,M,2016-06-08T08:50:51Z,2016-06-08T00:00:00Z,33,MARIA ORTIZ,0,0,0,0,0,0,No
110510,2.362182e+13,5757587,F,2016-06-01T09:35:48Z,2016-06-01T00:00:00Z,64,SOLON BORGES,0,0,0,0,0,0,No
110511,8.235996e+11,5786742,F,2016-06-08T08:50:20Z,2016-06-08T00:00:00Z,14,MARIA ORTIZ,0,0,0,0,0,0,No
110512,9.876246e+13,5786368,F,2016-06-08T08:20:01Z,2016-06-08T00:00:00Z,41,MARIA ORTIZ,0,0,0,0,0,0,No
110513,8.674778e+13,5785964,M,2016-06-08T07:52:55Z,2016-06-08T00:00:00Z,2,ANTÃ”NIO HONÃ“RIO,0,0,0,0,0,0,No
110514,2.695685e+12,5786567,F,2016-06-08T08:35:31Z,2016-06-08T00:00:00Z,58,MARIA ORTIZ,0,0,0,0,0,0,No
110515,6.456342e+14,5778621,M,2016-06-06T15:58:05Z,2016-06-08T00:00:00Z,33,MARIA ORTIZ,0,1,0,0,0,0,Yes
110516,6.923772e+13,5780205,F,2016-06-07T07:45:16Z,2016-06-08T00:00:00Z,37,MARIA ORTIZ,0,0,0,0,0,0,Yes
110517,5.574942e+12,5780122,F,2016-06-07T07:38:34Z,2016-06-07T00:00:00Z,19,MARIA ORTIZ,0,0,0,0,0,0,No
110518,7.263315e+13,5630375,F,2016-04-27T15:15:06Z,2016-06-07T00:00:00Z,50,MARIA ORTIZ,0,0,0,0,0,1,No
110519,6.542388e+13,5630447,F,2016-04-27T15:23:14Z,2016-06-07T00:00:00Z,22,MARIA ORTIZ,0,0,0,0,0,1,No
110520,9.969977e+14,5650534,F,2016-05-03T07:51:47Z,2016-06-07T00:00:00Z,42,MARIA ORTIZ,0,0,0,0,0,1,No
110521,3.635534e+13,5651072,F,2016-05-03T08:23:40Z,2016-06-07T00:00:00Z,53,MARIA ORTIZ,0,0,0,0,0,1,No
110522,2.572134e+12,5651768,F,2016-05-03T09:15:35Z,2016-06-07T00:00:00Z,56,MARIA ORTIZ,0,0,0,0,0,1,No
110523,3.596266e+12,5650093,F,2016-05-03T07:27:33Z,2016-06-07T00:00:00Z,51,MARIA ORTIZ,0,0,0,0,0,1,No
110524,1.557663e+13,5630692,F,2016-04-27T16:03:52Z,2016-06-07T00:00:00Z,21,MARIA ORTIZ,0,0,0,0,0,1,No
110525,9.213493e+13,5630323,F,2016-04-27T15:09:23Z,2016-06-07T00:00:00Z,38,MARIA ORTIZ,0,0,0,0,0,1,No
110526,3.775115e+14,5629448,F,2016-04-27T13:30:56Z,2016-06-07T00:00:00Z,54,MARIA ORTIZ,0,0,0,0,0,1,No

In [115]:
#changing key column name
df_new = df.rename(columns={'No-show':'Noshow'})
df_new

,PatientId,AppointmentID,Gender,ScheduledDay,AppointmentDay,Age,Neighbourhood,Scholarship,Hipertension,Diabetes,Alcoholism,Handcap,SMS_received,Noshow
0,2.987250e+13,5642903,F,2016-04-29T18:38:08Z,2016-04-29T00:00:00Z,62,JARDIM DA PENHA,0,1,0,0,0,0,No
1,5.589978e+14,5642503,M,2016-04-29T16:08:27Z,2016-04-29T00:00:00Z,56,JARDIM DA PENHA,0,0,0,0,0,0,No
2,4.262962e+12,5642549,F,2016-04-29T16:19:04Z,2016-04-29T00:00:00Z,62,MATA DA PRAIA,0,0,0,0,0,0,No
3,8.679512e+11,5642828,F,2016-04-29T17:29:31Z,2016-04-29T00:00:00Z,8,PONTAL DE CAMBURI,0,0,0,0,0,0,No
4,8.841186e+12,5642494,F,2016-04-29T16:07:23Z,2016-04-29T00:00:00Z,56,JARDIM DA PENHA,0,1,1,0,0,0,No
5,9.598513e+13,5626772,F,2016-04-27T08:36:51Z,2016-04-29T00:00:00Z,76,REPÃšBLICA,0,1,0,0,0,0,No
6,7.336882e+14,5630279,F,2016-04-27T15:05:12Z,2016-04-29T00:00:00Z,23,GOIABEIRAS,0,0,0,0,0,0,Yes
7,3.449833e+12,5630575,F,2016-04-27T15:39:58Z,2016-04-29T00:00:00Z,39,GOIABEIRAS,0,0,0,0,0,0,Yes
8,5.639473e+13,5638447,F,2016-04-29T08:02:16Z,2016-04-29T00:00:00Z,21,ANDORINHAS,0,0,0,0,0,0,No
9,7.812456e+13,5629123,F,2016-04-27T12:48:25Z,2016-04-29T00:00:00Z,19,CONQUISTA,0,0,0,0,0,0,No
10,7.345362e+14,5630213,F,2016-04-27T14:58:11Z,2016-04-29T00:00:00Z,30,NOVA PALESTINA,0,0,0,0,0,0,No
11,7.542951e+12,5620163,M,2016-04-26T08:44:12Z,2016-04-29T00:00:00Z,29,NOVA PALESTINA,0,0,0,0,0,1,Yes
12,5.666548e+14,5634718,F,2016-04-28T11:33:51Z,2016-04-29T00:00:00Z,22,NOVA PALESTINA,1,0,0,0,0,0,No
13,9.113946e+14,5636249,M,2016-04-28T14:52:07Z,2016-04-29T00:00:00Z,28,NOVA PALESTINA,0,0,0,0,0,0,No
14,9.988472e+13,5633951,F,2016-04-28T10:06:24Z,2016-04-29T00:00:00Z,54,NOVA PALESTINA,0,0,0,0,0,0,No
15,9.994839e+10,5620206,F,2016-04-26T08:47:27Z,2016-04-29T00:00:00Z,15,NOVA PALESTINA,0,0,0,0,0,1,No
16,8.457439e+13,5633121,M,2016-04-28T08:51:47Z,2016-04-29T00:00:00Z,50,NOVA PALESTINA,0,0,0,0,0,0,No
17,1.479497e+13,5633460,F,2016-04-28T09:28:57Z,2016-04-29T00:00:00Z,40,CONQUISTA,1,0,0,0,0,0,Yes
18,1.713538e+13,5621836,F,2016-04-26T10:54:18Z,2016-04-29T00:00:00Z,30,NOVA PALESTINA,1,0,0,0,0,1,No
19,7.223289e+12,5640433,F,2016-04-29T10:43:14Z,2016-04-29T00:00:00Z,46,DA PENHA,0,0,0,0,0,0,No
20,6.222575e+14,5626083,F,2016-04-27T07:51:14Z,2016-04-29T00:00:00Z,30,NOVA PALESTINA,0,0,0,0,0,0,Yes
21,1.215484e+13,5628338,F,2016-04-27T10:50:45Z,2016-04-29T00:00:00Z,4,CONQUISTA,0,0,0,0,0,0,Yes
22,8.632298e+14,5616091,M,2016-04-25T13:29:16Z,2016-04-29T00:00:00Z,13,CONQUISTA,0,0,0,0,0,1,Yes
23,2.137540e+14,5634142,F,2016-04-28T10:27:05Z,2016-04-29T00:00:00Z,46,CONQUISTA,0,0,0,0,0,0,No
24,8.734858e+12,5641780,F,2016-04-29T14:19:19Z,2016-04-29T00:00:00Z,65,TABUAZEIRO,0,0,0,0,0,0,No
25,5.819370e+12,5624020,M,2016-04-26T15:04:17Z,2016-04-29T00:00:00Z,46,CONQUISTA,0,1,0,0,0,1,No
26,2.578785e+10,5641781,F,2016-04-29T14:19:42Z,2016-04-29T00:00:00Z,45,BENTO FERREIRA,0,1,0,0,0,0,No
27,1.215484e+13,5628345,F,2016-04-27T10:51:45Z,2016-04-29T00:00:00Z,4,CONQUISTA,0,0,0,0,0,0,No
28,5.926172e+12,5642400,M,2016-04-29T15:48:02Z,2016-04-29T00:00:00Z,51,SÃƒO PEDRO,0,0,0,0,0,0,No
29,1.225776e+12,5642186,F,2016-04-29T15:16:29Z,2016-04-29T00:00:00Z,32,SANTA MARTHA,0,0,0,0,0,0,No
...,...,...,...,...,...,...,...,...,...,...,...,...,...,...
110497,7.935892e+14,5757745,M,2016-06-01T09:46:33Z,2016-06-01T00:00:00Z,76,MARIA ORTIZ,0,0,0,0,0,0,No
110498,9.433654e+13,5787655,F,2016-06-08T10:21:14Z,2016-06-08T00:00:00Z,59,MARIA ORTIZ,0,0,0,0,0,0,No
110499,8.219692e+14,5757697,F,2016-06-01T09:42:56Z,2016-06-01T00:00:00Z,66,MARIA ORTIZ,0,1,1,0,0,0,No
110500,4.434384e+14,5787233,F,2016-06-08T09:35:13Z,2016-06-08T00:00:00Z,59,MARIA ORTIZ,0,0,0,0,0,0,No
110501,4.544252e+11,5758133,M,2016-06-01T10:19:12Z,2016-06-01T00:00:00Z,44,MARIA ORTIZ,0,0,0,0,0,0,No
110502,7.316229e+14,5787937,F,2016-06-08T10:50:42Z,2016-06-08T00:00:00Z,22,GOIABEIRAS,0,0,0,0,0,0,No
110503,2.362182e+13,5759473,F,2016-06-01T13:00:36Z,2016-06-01T00:00:00Z,64,SOLON BORGES,0,0,0,0,0,0,No
110504,9.947983e+12,5788052,F,2016-06-08T11:06:21Z,2016-06-08T00:00:00Z,4,MARIA ORTIZ,0,0,0,0,0,0,No
110505,5.667344e+13,5758455,F,2016-06-01T10:45:50Z,2016-06-01T00:00:00Z,55,MARIA ORTIZ,0,0,0,0,0,0,No
110506,8.973883e+11,5758779,M,2016-06-01T11:09:20Z,2016-06-01T00:00:00Z,5,MARIA ORTIZ,0,0,0,0,0,0,No
110507,4.769462e+14,5786918,F,2016-06-08T09:04:18Z,2016-06-08T00:00:00Z,0,MARIA ORTIZ,0,0,0,0,0,0,No
110508,9.433654e+13,5757656,F,2016-06-01T09:41:00Z,2016-06-01T00:00:00Z,59,MARIA ORTIZ,0,0,0,0,0,0,No
110509,4.952968e+14,5786750,M,2016-06-08T08:50:51Z,2016-06-08T00:00:00Z,33,MARIA ORTIZ,0,0,0,0,0,0,No
110510,2.362182e+13,5757587,F,2016-06-01T09:35:48Z,2016-06-01T00:00:00Z,64,SOLON BORGES,0,0,0,0,0,0,No
110511,8.235996e+11,5786742,F,2016-06-08T08:50:20Z,2016-06-08T00:00:00Z,14,MARIA ORTIZ,0,0,0,0,0,0,No
110512,9.876246e+13,5786368,F,2016-06-08T08:20:01Z,2016-06-08T00:00:00Z,41,MARIA ORTIZ,0,0,0,0,0,0,No
110513,8.674778e+13,5785964,M,2016-06-08T07:52:55Z,2016-06-08T00:00:00Z,2,ANTÃ”NIO HONÃ“RIO,0,0,0,0,0,0,No
110514,2.695685e+12,5786567,F,2016-06-08T08:35:31Z,2016-06-08T00:00:00Z,58,MARIA ORTIZ,0,0,0,0,0,0,No
110515,6.456342e+14,5778621,M,2016-06-06T15:58:05Z,2016-06-08T00:00:00Z,33,MARIA ORTIZ,0,1,0,0,0,0,Yes
110516,6.923772e+13,5780205,F,2016-06-07T07:45:16Z,2016-06-08T00:00:00Z,37,MARIA ORTIZ,0,0,0,0,0,0,Yes
110517,5.574942e+12,5780122,F,2016-06-07T07:38:34Z,2016-06-07T00:00:00Z,19,MARIA ORTIZ,0,0,0,0,0,0,No
110518,7.263315e+13,5630375,F,2016-04-27T15:15:06Z,2016-06-07T00:00:00Z,50,MARIA ORTIZ,0,0,0,0,0,1,No
110519,6.542388e+13,5630447,F,2016-04-27T15:23:14Z,2016-06-07T00:00:00Z,22,MARIA ORTIZ,0,0,0,0,0,1,No
110520,9.969977e+14,5650534,F,2016-05-03T07:51:47Z,2016-06-07T00:00:00Z,42,MARIA ORTIZ,0,0,0,0,0,1,No
110521,3.635534e+13,5651072,F,2016-05-03T08:23:40Z,2016-06-07T00:00:00Z,53,MARIA ORTIZ,0,0,0,0,0,1,No
110522,2.572134e+12,5651768,F,2016-05-03T09:15:35Z,2016-06-07T00:00:00Z,56,MARIA ORTIZ,0,0,0,0,0,1,No
110523,3.596266e+12,5650093,F,2016-05-03T07:27:33Z,2016-06-07T00:00:00Z,51,MARIA ORTIZ,0,0,0,0,0,1,No
110524,1.557663e+13,5630692,F,2016-04-27T16:03:52Z,2016-06-07T00:00:00Z,21,MARIA ORTIZ,0,0,0,0,0,1,No
110525,9.213493e+13,5630323,F,2016-04-27T15:09:23Z,2016-06-07T00:00:00Z,38,MARIA ORTIZ,0,0,0,0,0,1,No
110526,3.775115e+14,5629448,F,2016-04-27T13:30:56Z,2016-06-07T00:00:00Z,54,MARIA ORTIZ,0,0,0,0,0,1,No

In [116]:
#changing noshow data into integer in order to calculate
df_new.loc[df_new['Noshow'] == 'Yes', 'Noshow'] = 1
df_new.loc[df_new['Noshow'] == 'No', 'Noshow'] = 0
df_new

,PatientId,AppointmentID,Gender,ScheduledDay,AppointmentDay,Age,Neighbourhood,Scholarship,Hipertension,Diabetes,Alcoholism,Handcap,SMS_received,Noshow
0,2.987250e+13,5642903,F,2016-04-29T18:38:08Z,2016-04-29T00:00:00Z,62,JARDIM DA PENHA,0,1,0,0,0,0,0
1,5.589978e+14,5642503,M,2016-04-29T16:08:27Z,2016-04-29T00:00:00Z,56,JARDIM DA PENHA,0,0,0,0,0,0,0
2,4.262962e+12,5642549,F,2016-04-29T16:19:04Z,2016-04-29T00:00:00Z,62,MATA DA PRAIA,0,0,0,0,0,0,0
3,8.679512e+11,5642828,F,2016-04-29T17:29:31Z,2016-04-29T00:00:00Z,8,PONTAL DE CAMBURI,0,0,0,0,0,0,0
4,8.841186e+12,5642494,F,2016-04-29T16:07:23Z,2016-04-29T00:00:00Z,56,JARDIM DA PENHA,0,1,1,0,0,0,0
5,9.598513e+13,5626772,F,2016-04-27T08:36:51Z,2016-04-29T00:00:00Z,76,REPÃšBLICA,0,1,0,0,0,0,0
6,7.336882e+14,5630279,F,2016-04-27T15:05:12Z,2016-04-29T00:00:00Z,23,GOIABEIRAS,0,0,0,0,0,0,1
7,3.449833e+12,5630575,F,2016-04-27T15:39:58Z,2016-04-29T00:00:00Z,39,GOIABEIRAS,0,0,0,0,0,0,1
8,5.639473e+13,5638447,F,2016-04-29T08:02:16Z,2016-04-29T00:00:00Z,21,ANDORINHAS,0,0,0,0,0,0,0
9,7.812456e+13,5629123,F,2016-04-27T12:48:25Z,2016-04-29T00:00:00Z,19,CONQUISTA,0,0,0,0,0,0,0
10,7.345362e+14,5630213,F,2016-04-27T14:58:11Z,2016-04-29T00:00:00Z,30,NOVA PALESTINA,0,0,0,0,0,0,0
11,7.542951e+12,5620163,M,2016-04-26T08:44:12Z,2016-04-29T00:00:00Z,29,NOVA PALESTINA,0,0,0,0,0,1,1
12,5.666548e+14,5634718,F,2016-04-28T11:33:51Z,2016-04-29T00:00:00Z,22,NOVA PALESTINA,1,0,0,0,0,0,0
13,9.113946e+14,5636249,M,2016-04-28T14:52:07Z,2016-04-29T00:00:00Z,28,NOVA PALESTINA,0,0,0,0,0,0,0
14,9.988472e+13,5633951,F,2016-04-28T10:06:24Z,2016-04-29T00:00:00Z,54,NOVA PALESTINA,0,0,0,0,0,0,0
15,9.994839e+10,5620206,F,2016-04-26T08:47:27Z,2016-04-29T00:00:00Z,15,NOVA PALESTINA,0,0,0,0,0,1,0
16,8.457439e+13,5633121,M,2016-04-28T08:51:47Z,2016-04-29T00:00:00Z,50,NOVA PALESTINA,0,0,0,0,0,0,0
17,1.479497e+13,5633460,F,2016-04-28T09:28:57Z,2016-04-29T00:00:00Z,40,CONQUISTA,1,0,0,0,0,0,1
18,1.713538e+13,5621836,F,2016-04-26T10:54:18Z,2016-04-29T00:00:00Z,30,NOVA PALESTINA,1,0,0,0,0,1,0
19,7.223289e+12,5640433,F,2016-04-29T10:43:14Z,2016-04-29T00:00:00Z,46,DA PENHA,0,0,0,0,0,0,0
20,6.222575e+14,5626083,F,2016-04-27T07:51:14Z,2016-04-29T00:00:00Z,30,NOVA PALESTINA,0,0,0,0,0,0,1
21,1.215484e+13,5628338,F,2016-04-27T10:50:45Z,2016-04-29T00:00:00Z,4,CONQUISTA,0,0,0,0,0,0,1
22,8.632298e+14,5616091,M,2016-04-25T13:29:16Z,2016-04-29T00:00:00Z,13,CONQUISTA,0,0,0,0,0,1,1
23,2.137540e+14,5634142,F,2016-04-28T10:27:05Z,2016-04-29T00:00:00Z,46,CONQUISTA,0,0,0,0,0,0,0
24,8.734858e+12,5641780,F,2016-04-29T14:19:19Z,2016-04-29T00:00:00Z,65,TABUAZEIRO,0,0,0,0,0,0,0
25,5.819370e+12,5624020,M,2016-04-26T15:04:17Z,2016-04-29T00:00:00Z,46,CONQUISTA,0,1,0,0,0,1,0
26,2.578785e+10,5641781,F,2016-04-29T14:19:42Z,2016-04-29T00:00:00Z,45,BENTO FERREIRA,0,1,0,0,0,0,0
27,1.215484e+13,5628345,F,2016-04-27T10:51:45Z,2016-04-29T00:00:00Z,4,CONQUISTA,0,0,0,0,0,0,0
28,5.926172e+12,5642400,M,2016-04-29T15:48:02Z,2016-04-29T00:00:00Z,51,SÃƒO PEDRO,0,0,0,0,0,0,0
29,1.225776e+12,5642186,F,2016-04-29T15:16:29Z,2016-04-29T00:00:00Z,32,SANTA MARTHA,0,0,0,0,0,0,0
...,...,...,...,...,...,...,...,...,...,...,...,...,...,...
110497,7.935892e+14,5757745,M,2016-06-01T09:46:33Z,2016-06-01T00:00:00Z,76,MARIA ORTIZ,0,0,0,0,0,0,0
110498,9.433654e+13,5787655,F,2016-06-08T10:21:14Z,2016-06-08T00:00:00Z,59,MARIA ORTIZ,0,0,0,0,0,0,0
110499,8.219692e+14,5757697,F,2016-06-01T09:42:56Z,2016-06-01T00:00:00Z,66,MARIA ORTIZ,0,1,1,0,0,0,0
110500,4.434384e+14,5787233,F,2016-06-08T09:35:13Z,2016-06-08T00:00:00Z,59,MARIA ORTIZ,0,0,0,0,0,0,0
110501,4.544252e+11,5758133,M,2016-06-01T10:19:12Z,2016-06-01T00:00:00Z,44,MARIA ORTIZ,0,0,0,0,0,0,0
110502,7.316229e+14,5787937,F,2016-06-08T10:50:42Z,2016-06-08T00:00:00Z,22,GOIABEIRAS,0,0,0,0,0,0,0
110503,2.362182e+13,5759473,F,2016-06-01T13:00:36Z,2016-06-01T00:00:00Z,64,SOLON BORGES,0,0,0,0,0,0,0
110504,9.947983e+12,5788052,F,2016-06-08T11:06:21Z,2016-06-08T00:00:00Z,4,MARIA ORTIZ,0,0,0,0,0,0,0
110505,5.667344e+13,5758455,F,2016-06-01T10:45:50Z,2016-06-01T00:00:00Z,55,MARIA ORTIZ,0,0,0,0,0,0,0
110506,8.973883e+11,5758779,M,2016-06-01T11:09:20Z,2016-06-01T00:00:00Z,5,MARIA ORTIZ,0,0,0,0,0,0,0
110507,4.769462e+14,5786918,F,2016-06-08T09:04:18Z,2016-06-08T00:00:00Z,0,MARIA ORTIZ,0,0,0,0,0,0,0
110508,9.433654e+13,5757656,F,2016-06-01T09:41:00Z,2016-06-01T00:00:00Z,59,MARIA ORTIZ,0,0,0,0,0,0,0
110509,4.952968e+14,5786750,M,2016-06-08T08:50:51Z,2016-06-08T00:00:00Z,33,MARIA ORTIZ,0,0,0,0,0,0,0
110510,2.362182e+13,5757587,F,2016-06-01T09:35:48Z,2016-06-01T00:00:00Z,64,SOLON BORGES,0,0,0,0,0,0,0
110511,8.235996e+11,5786742,F,2016-06-08T08:50:20Z,2016-06-08T00:00:00Z,14,MARIA ORTIZ,0,0,0,0,0,0,0
110512,9.876246e+13,5786368,F,2016-06-08T08:20:01Z,2016-06-08T00:00:00Z,41,MARIA ORTIZ,0,0,0,0,0,0,0
110513,8.674778e+13,5785964,M,2016-06-08T07:52:55Z,2016-06-08T00:00:00Z,2,ANTÃ”NIO HONÃ“RIO,0,0,0,0,0,0,0
110514,2.695685e+12,5786567,F,2016-06-08T08:35:31Z,2016-06-08T00:00:00Z,58,MARIA ORTIZ,0,0,0,0,0,0,0
110515,6.456342e+14,5778621,M,2016-06-06T15:58:05Z,2016-06-08T00:00:00Z,33,MARIA ORTIZ,0,1,0,0,0,0,1
110516,6.923772e+13,5780205,F,2016-06-07T07:45:16Z,2016-06-08T00:00:00Z,37,MARIA ORTIZ,0,0,0,0,0,0,1
110517,5.574942e+12,5780122,F,2016-06-07T07:38:34Z,2016-06-07T00:00:00Z,19,MARIA ORTIZ,0,0,0,0,0,0,0
110518,7.263315e+13,5630375,F,2016-04-27T15:15:06Z,2016-06-07T00:00:00Z,50,MARIA ORTIZ,0,0,0,0,0,1,0
110519,6.542388e+13,5630447,F,2016-04-27T15:23:14Z,2016-06-07T00:00:00Z,22,MARIA ORTIZ,0,0,0,0,0,1,0
110520,9.969977e+14,5650534,F,2016-05-03T07:51:47Z,2016-06-07T00:00:00Z,42,MARIA ORTIZ,0,0,0,0,0,1,0
110521,3.635534e+13,5651072,F,2016-05-03T08:23:40Z,2016-06-07T00:00:00Z,53,MARIA ORTIZ,0,0,0,0,0,1,0
110522,2.572134e+12,5651768,F,2016-05-03T09:15:35Z,2016-06-07T00:00:00Z,56,MARIA ORTIZ,0,0,0,0,0,1,0
110523,3.596266e+12,5650093,F,2016-05-03T07:27:33Z,2016-06-07T00:00:00Z,51,MARIA ORTIZ,0,0,0,0,0,1,0
110524,1.557663e+13,5630692,F,2016-04-27T16:03:52Z,2016-06-07T00:00:00Z,21,MARIA ORTIZ,0,0,0,0,0,1,0
110525,9.213493e+13,5630323,F,2016-04-27T15:09:23Z,2016-06-07T00:00:00Z,38,MARIA ORTIZ,0,0,0,0,0,1,0
110526,3.775115e+14,5629448,F,2016-04-27T13:30:56Z,2016-06-07T00:00:00Z,54,MARIA ORTIZ,0,0,0,0,0,1,0

In [117]:
#changing appointmentday and scheduledday data into datetime type data
df_new['AppointmentDay'] = pd.to_datetime(df_new['AppointmentDay'])
df_new['ScheduledDay'] = pd.to_datetime(df_new['ScheduledDay'])
df_new

,PatientId,AppointmentID,Gender,ScheduledDay,AppointmentDay,Age,Neighbourhood,Scholarship,Hipertension,Diabetes,Alcoholism,Handcap,SMS_received,Noshow
0,2.987250e+13,5642903,F,2016-04-29 18:38:08,2016-04-29,62,JARDIM DA PENHA,0,1,0,0,0,0,0
1,5.589978e+14,5642503,M,2016-04-29 16:08:27,2016-04-29,56,JARDIM DA PENHA,0,0,0,0,0,0,0
2,4.262962e+12,5642549,F,2016-04-29 16:19:04,2016-04-29,62,MATA DA PRAIA,0,0,0,0,0,0,0
3,8.679512e+11,5642828,F,2016-04-29 17:29:31,2016-04-29,8,PONTAL DE CAMBURI,0,0,0,0,0,0,0
4,8.841186e+12,5642494,F,2016-04-29 16:07:23,2016-04-29,56,JARDIM DA PENHA,0,1,1,0,0,0,0
5,9.598513e+13,5626772,F,2016-04-27 08:36:51,2016-04-29,76,REPÃšBLICA,0,1,0,0,0,0,0
6,7.336882e+14,5630279,F,2016-04-27 15:05:12,2016-04-29,23,GOIABEIRAS,0,0,0,0,0,0,1
7,3.449833e+12,5630575,F,2016-04-27 15:39:58,2016-04-29,39,GOIABEIRAS,0,0,0,0,0,0,1
8,5.639473e+13,5638447,F,2016-04-29 08:02:16,2016-04-29,21,ANDORINHAS,0,0,0,0,0,0,0
9,7.812456e+13,5629123,F,2016-04-27 12:48:25,2016-04-29,19,CONQUISTA,0,0,0,0,0,0,0
10,7.345362e+14,5630213,F,2016-04-27 14:58:11,2016-04-29,30,NOVA PALESTINA,0,0,0,0,0,0,0
11,7.542951e+12,5620163,M,2016-04-26 08:44:12,2016-04-29,29,NOVA PALESTINA,0,0,0,0,0,1,1
12,5.666548e+14,5634718,F,2016-04-28 11:33:51,2016-04-29,22,NOVA PALESTINA,1,0,0,0,0,0,0
13,9.113946e+14,5636249,M,2016-04-28 14:52:07,2016-04-29,28,NOVA PALESTINA,0,0,0,0,0,0,0
14,9.988472e+13,5633951,F,2016-04-28 10:06:24,2016-04-29,54,NOVA PALESTINA,0,0,0,0,0,0,0
15,9.994839e+10,5620206,F,2016-04-26 08:47:27,2016-04-29,15,NOVA PALESTINA,0,0,0,0,0,1,0
16,8.457439e+13,5633121,M,2016-04-28 08:51:47,2016-04-29,50,NOVA PALESTINA,0,0,0,0,0,0,0
17,1.479497e+13,5633460,F,2016-04-28 09:28:57,2016-04-29,40,CONQUISTA,1,0,0,0,0,0,1
18,1.713538e+13,5621836,F,2016-04-26 10:54:18,2016-04-29,30,NOVA PALESTINA,1,0,0,0,0,1,0
19,7.223289e+12,5640433,F,2016-04-29 10:43:14,2016-04-29,46,DA PENHA,0,0,0,0,0,0,0
20,6.222575e+14,5626083,F,2016-04-27 07:51:14,2016-04-29,30,NOVA PALESTINA,0,0,0,0,0,0,1
21,1.215484e+13,5628338,F,2016-04-27 10:50:45,2016-04-29,4,CONQUISTA,0,0,0,0,0,0,1
22,8.632298e+14,5616091,M,2016-04-25 13:29:16,2016-04-29,13,CONQUISTA,0,0,0,0,0,1,1
23,2.137540e+14,5634142,F,2016-04-28 10:27:05,2016-04-29,46,CONQUISTA,0,0,0,0,0,0,0
24,8.734858e+12,5641780,F,2016-04-29 14:19:19,2016-04-29,65,TABUAZEIRO,0,0,0,0,0,0,0
25,5.819370e+12,5624020,M,2016-04-26 15:04:17,2016-04-29,46,CONQUISTA,0,1,0,0,0,1,0
26,2.578785e+10,5641781,F,2016-04-29 14:19:42,2016-04-29,45,BENTO FERREIRA,0,1,0,0,0,0,0
27,1.215484e+13,5628345,F,2016-04-27 10:51:45,2016-04-29,4,CONQUISTA,0,0,0,0,0,0,0
28,5.926172e+12,5642400,M,2016-04-29 15:48:02,2016-04-29,51,SÃƒO PEDRO,0,0,0,0,0,0,0
29,1.225776e+12,5642186,F,2016-04-29 15:16:29,2016-04-29,32,SANTA MARTHA,0,0,0,0,0,0,0
...,...,...,...,...,...,...,...,...,...,...,...,...,...,...
110497,7.935892e+14,5757745,M,2016-06-01 09:46:33,2016-06-01,76,MARIA ORTIZ,0,0,0,0,0,0,0
110498,9.433654e+13,5787655,F,2016-06-08 10:21:14,2016-06-08,59,MARIA ORTIZ,0,0,0,0,0,0,0
110499,8.219692e+14,5757697,F,2016-06-01 09:42:56,2016-06-01,66,MARIA ORTIZ,0,1,1,0,0,0,0
110500,4.434384e+14,5787233,F,2016-06-08 09:35:13,2016-06-08,59,MARIA ORTIZ,0,0,0,0,0,0,0
110501,4.544252e+11,5758133,M,2016-06-01 10:19:12,2016-06-01,44,MARIA ORTIZ,0,0,0,0,0,0,0
110502,7.316229e+14,5787937,F,2016-06-08 10:50:42,2016-06-08,22,GOIABEIRAS,0,0,0,0,0,0,0
110503,2.362182e+13,5759473,F,2016-06-01 13:00:36,2016-06-01,64,SOLON BORGES,0,0,0,0,0,0,0
110504,9.947983e+12,5788052,F,2016-06-08 11:06:21,2016-06-08,4,MARIA ORTIZ,0,0,0,0,0,0,0
110505,5.667344e+13,5758455,F,2016-06-01 10:45:50,2016-06-01,55,MARIA ORTIZ,0,0,0,0,0,0,0
110506,8.973883e+11,5758779,M,2016-06-01 11:09:20,2016-06-01,5,MARIA ORTIZ,0,0,0,0,0,0,0
110507,4.769462e+14,5786918,F,2016-06-08 09:04:18,2016-06-08,0,MARIA ORTIZ,0,0,0,0,0,0,0
110508,9.433654e+13,5757656,F,2016-06-01 09:41:00,2016-06-01,59,MARIA ORTIZ,0,0,0,0,0,0,0
110509,4.952968e+14,5786750,M,2016-06-08 08:50:51,2016-06-08,33,MARIA ORTIZ,0,0,0,0,0,0,0
110510,2.362182e+13,5757587,F,2016-06-01 09:35:48,2016-06-01,64,SOLON BORGES,0,0,0,0,0,0,0
110511,8.235996e+11,5786742,F,2016-06-08 08:50:20,2016-06-08,14,MARIA ORTIZ,0,0,0,0,0,0,0
110512,9.876246e+13,5786368,F,2016-06-08 08:20:01,2016-06-08,41,MARIA ORTIZ,0,0,0,0,0,0,0
110513,8.674778e+13,5785964,M,2016-06-08 07:52:55,2016-06-08,2,ANTÃ”NIO HONÃ“RIO,0,0,0,0,0,0,0
110514,2.695685e+12,5786567,F,2016-06-08 08:35:31,2016-06-08,58,MARIA ORTIZ,0,0,0,0,0,0,0
110515,6.456342e+14,5778621,M,2016-06-06 15:58:05,2016-06-08,33,MARIA ORTIZ,0,1,0,0,0,0,1
110516,6.923772e+13,5780205,F,2016-06-07 07:45:16,2016-06-08,37,MARIA ORTIZ,0,0,0,0,0,0,1
110517,5.574942e+12,5780122,F,2016-06-07 07:38:34,2016-06-07,19,MARIA ORTIZ,0,0,0,0,0,0,0
110518,7.263315e+13,5630375,F,2016-04-27 15:15:06,2016-06-07,50,MARIA ORTIZ,0,0,0,0,0,1,0
110519,6.542388e+13,5630447,F,2016-04-27 15:23:14,2016-06-07,22,MARIA ORTIZ,0,0,0,0,0,1,0
110520,9.969977e+14,5650534,F,2016-05-03 07:51:47,2016-06-07,42,MARIA ORTIZ,0,0,0,0,0,1,0
110521,3.635534e+13,5651072,F,2016-05-03 08:23:40,2016-06-07,53,MARIA ORTIZ,0,0,0,0,0,1,0
110522,2.572134e+12,5651768,F,2016-05-03 09:15:35,2016-06-07,56,MARIA ORTIZ,0,0,0,0,0,1,0
110523,3.596266e+12,5650093,F,2016-05-03 07:27:33,2016-06-07,51,MARIA ORTIZ,0,0,0,0,0,1,0
110524,1.557663e+13,5630692,F,2016-04-27 16:03:52,2016-06-07,21,MARIA ORTIZ,0,0,0,0,0,1,0
110525,9.213493e+13,5630323,F,2016-04-27 15:09:23,2016-06-07,38,MARIA ORTIZ,0,0,0,0,0,1,0
110526,3.775115e+14,5629448,F,2016-04-27 13:30:56,2016-06-07,54,MARIA ORTIZ,0,0,0,0,0,1,0

In [118]:
#checking datatypes
df_new.dtypes

PatientId                float64
AppointmentID              int64
Gender                    object
ScheduledDay      datetime64[ns]
AppointmentDay    datetime64[ns]
Age                        int64
Neighbourhood             object
Scholarship                int64
Hipertension               int64
Diabetes                   int64
Alcoholism                 int64
Handcap                    int64
SMS_received               int64
Noshow                     int64
dtype: object

In [119]:
#adding waiting days data to a new column
df_new['Daystoshow'] = df_new['AppointmentDay'] - df_new['ScheduledDay']
df_new

,PatientId,AppointmentID,Gender,ScheduledDay,AppointmentDay,Age,Neighbourhood,Scholarship,Hipertension,Diabetes,Alcoholism,Handcap,SMS_received,Noshow,Daystoshow
0,2.987250e+13,5642903,F,2016-04-29 18:38:08,2016-04-29,62,JARDIM DA PENHA,0,1,0,0,0,0,0,-1 days +05:21:52
1,5.589978e+14,5642503,M,2016-04-29 16:08:27,2016-04-29,56,JARDIM DA PENHA,0,0,0,0,0,0,0,-1 days +07:51:33
2,4.262962e+12,5642549,F,2016-04-29 16:19:04,2016-04-29,62,MATA DA PRAIA,0,0,0,0,0,0,0,-1 days +07:40:56
3,8.679512e+11,5642828,F,2016-04-29 17:29:31,2016-04-29,8,PONTAL DE CAMBURI,0,0,0,0,0,0,0,-1 days +06:30:29
4,8.841186e+12,5642494,F,2016-04-29 16:07:23,2016-04-29,56,JARDIM DA PENHA,0,1,1,0,0,0,0,-1 days +07:52:37
5,9.598513e+13,5626772,F,2016-04-27 08:36:51,2016-04-29,76,REPÃšBLICA,0,1,0,0,0,0,0,1 days 15:23:09
6,7.336882e+14,5630279,F,2016-04-27 15:05:12,2016-04-29,23,GOIABEIRAS,0,0,0,0,0,0,1,1 days 08:54:48
7,3.449833e+12,5630575,F,2016-04-27 15:39:58,2016-04-29,39,GOIABEIRAS,0,0,0,0,0,0,1,1 days 08:20:02
8,5.639473e+13,5638447,F,2016-04-29 08:02:16,2016-04-29,21,ANDORINHAS,0,0,0,0,0,0,0,-1 days +15:57:44
9,7.812456e+13,5629123,F,2016-04-27 12:48:25,2016-04-29,19,CONQUISTA,0,0,0,0,0,0,0,1 days 11:11:35
10,7.345362e+14,5630213,F,2016-04-27 14:58:11,2016-04-29,30,NOVA PALESTINA,0,0,0,0,0,0,0,1 days 09:01:49
11,7.542951e+12,5620163,M,2016-04-26 08:44:12,2016-04-29,29,NOVA PALESTINA,0,0,0,0,0,1,1,2 days 15:15:48
12,5.666548e+14,5634718,F,2016-04-28 11:33:51,2016-04-29,22,NOVA PALESTINA,1,0,0,0,0,0,0,0 days 12:26:09
13,9.113946e+14,5636249,M,2016-04-28 14:52:07,2016-04-29,28,NOVA PALESTINA,0,0,0,0,0,0,0,0 days 09:07:53
14,9.988472e+13,5633951,F,2016-04-28 10:06:24,2016-04-29,54,NOVA PALESTINA,0,0,0,0,0,0,0,0 days 13:53:36
15,9.994839e+10,5620206,F,2016-04-26 08:47:27,2016-04-29,15,NOVA PALESTINA,0,0,0,0,0,1,0,2 days 15:12:33
16,8.457439e+13,5633121,M,2016-04-28 08:51:47,2016-04-29,50,NOVA PALESTINA,0,0,0,0,0,0,0,0 days 15:08:13
17,1.479497e+13,5633460,F,2016-04-28 09:28:57,2016-04-29,40,CONQUISTA,1,0,0,0,0,0,1,0 days 14:31:03
18,1.713538e+13,5621836,F,2016-04-26 10:54:18,2016-04-29,30,NOVA PALESTINA,1,0,0,0,0,1,0,2 days 13:05:42
19,7.223289e+12,5640433,F,2016-04-29 10:43:14,2016-04-29,46,DA PENHA,0,0,0,0,0,0,0,-1 days +13:16:46
20,6.222575e+14,5626083,F,2016-04-27 07:51:14,2016-04-29,30,NOVA PALESTINA,0,0,0,0,0,0,1,1 days 16:08:46
21,1.215484e+13,5628338,F,2016-04-27 10:50:45,2016-04-29,4,CONQUISTA,0,0,0,0,0,0,1,1 days 13:09:15
22,8.632298e+14,5616091,M,2016-04-25 13:29:16,2016-04-29,13,CONQUISTA,0,0,0,0,0,1,1,3 days 10:30:44
23,2.137540e+14,5634142,F,2016-04-28 10:27:05,2016-04-29,46,CONQUISTA,0,0,0,0,0,0,0,0 days 13:32:55
24,8.734858e+12,5641780,F,2016-04-29 14:19:19,2016-04-29,65,TABUAZEIRO,0,0,0,0,0,0,0,-1 days +09:40:41
25,5.819370e+12,5624020,M,2016-04-26 15:04:17,2016-04-29,46,CONQUISTA,0,1,0,0,0,1,0,2 days 08:55:43
26,2.578785e+10,5641781,F,2016-04-29 14:19:42,2016-04-29,45,BENTO FERREIRA,0,1,0,0,0,0,0,-1 days +09:40:18
27,1.215484e+13,5628345,F,2016-04-27 10:51:45,2016-04-29,4,CONQUISTA,0,0,0,0,0,0,0,1 days 13:08:15
28,5.926172e+12,5642400,M,2016-04-29 15:48:02,2016-04-29,51,SÃƒO PEDRO,0,0,0,0,0,0,0,-1 days +08:11:58
29,1.225776e+12,5642186,F,2016-04-29 15:16:29,2016-04-29,32,SANTA MARTHA,0,0,0,0,0,0,0,-1 days +08:43:31
...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...
110497,7.935892e+14,5757745,M,2016-06-01 09:46:33,2016-06-01,76,MARIA ORTIZ,0,0,0,0,0,0,0,-1 days +14:13:27
110498,9.433654e+13,5787655,F,2016-06-08 10:21:14,2016-06-08,59,MARIA ORTIZ,0,0,0,0,0,0,0,-1 days +13:38:46
110499,8.219692e+14,5757697,F,2016-06-01 09:42:56,2016-06-01,66,MARIA ORTIZ,0,1,1,0,0,0,0,-1 days +14:17:04
110500,4.434384e+14,5787233,F,2016-06-08 09:35:13,2016-06-08,59,MARIA ORTIZ,0,0,0,0,0,0,0,-1 days +14:24:47
110501,4.544252e+11,5758133,M,2016-06-01 10:19:12,2016-06-01,44,MARIA ORTIZ,0,0,0,0,0,0,0,-1 days +13:40:48
110502,7.316229e+14,5787937,F,2016-06-08 10:50:42,2016-06-08,22,GOIABEIRAS,0,0,0,0,0,0,0,-1 days +13:09:18
110503,2.362182e+13,5759473,F,2016-06-01 13:00:36,2016-06-01,64,SOLON BORGES,0,0,0,0,0,0,0,-1 days +10:59:24
110504,9.947983e+12,5788052,F,2016-06-08 11:06:21,2016-06-08,4,MARIA ORTIZ,0,0,0,0,0,0,0,-1 days +12:53:39
110505,5.667344e+13,5758455,F,2016-06-01 10:45:50,2016-06-01,55,MARIA ORTIZ,0,0,0,0,0,0,0,-1 days +13:14:10
110506,8.973883e+11,5758779,M,2016-06-01 11:09:20,2016-06-01,5,MARIA ORTIZ,0,0,0,0,0,0,0,-1 days +12:50:40
110507,4.769462e+14,5786918,F,2016-06-08 09:04:18,2016-06-08,0,MARIA ORTIZ,0,0,0,0,0,0,0,-1 days +14:55:42
110508,9.433654e+13,5757656,F,2016-06-01 09:41:00,2016-06-01,59,MARIA ORTIZ,0,0,0,0,0,0,0,-1 days +14:19:00
110509,4.952968e+14,5786750,M,2016-06-08 08:50:51,2016-06-08,33,MARIA ORTIZ,0,0,0,0,0,0,0,-1 days +15:09:09
110510,2.362182e+13,5757587,F,2016-06-01 09:35:48,2016-06-01,64,SOLON BORGES,0,0,0,0,0,0,0,-1 days +14:24:12
110511,8.235996e+11,5786742,F,2016-06-08 08:50:20,2016-06-08,14,MARIA ORTIZ,0,0,0,0,0,0,0,-1 days +15:09:40
110512,9.876246e+13,5786368,F,2016-06-08 08:20:01,2016-06-08,41,MARIA ORTIZ,0,0,0,0,0,0,0,-1 days +15:39:59
110513,8.674778e+13,5785964,M,2016-06-08 07:52:55,2016-06-08,2,ANTÃ”NIO HONÃ“RIO,0,0,0,0,0,0,0,-1 days +16:07:05
110514,2.695685e+12,5786567,F,2016-06-08 08:35:31,2016-06-08,58,MARIA ORTIZ,0,0,0,0,0,0,0,-1 days +15:24:29
110515,6.456342e+14,5778621,M,2016-06-06 15:58:05,2016-06-08,33,MARIA ORTIZ,0,1,0,0,0,0,1,1 days 08:01:55
110516,6.923772e+13,5780205,F,2016-06-07 07:45:16,2016-06-08,37,MARIA ORTIZ,0,0,0,0,0,0,1,0 days 16:14:44
110517,5.574942e+12,5780122,F,2016-06-07 07:38:34,2016-06-07,19,MARIA ORTIZ,0,0,0,0,0,0,0,-1 days +16:21:26
110518,7.263315e+13,5630375,F,2016-04-27 15:15:06,2016-06-07,50,MARIA ORTIZ,0,0,0,0,0,1,0,40 days 08:44:54
110519,6.542388e+13,5630447,F,2016-04-27 15:23:14,2016-06-07,22,MARIA ORTIZ,0,0,0,0,0,1,0,40 days 08:36:46
110520,9.969977e+14,5650534,F,2016-05-03 07:51:47,2016-06-07,42,MARIA ORTIZ,0,0,0,0,0,1,0,34 days 16:08:13
110521,3.635534e+13,5651072,F,2016-05-03 08:23:40,2016-06-07,53,MARIA ORTIZ,0,0,0,0,0,1,0,34 days 15:36:20
110522,2.572134e+12,5651768,F,2016-05-03 09:15:35,2016-06-07,56,MARIA ORTIZ,0,0,0,0,0,1,0,34 days 14:44:25
110523,3.596266e+12,5650093,F,2016-05-03 07:27:33,2016-06-07,51,MARIA ORTIZ,0,0,0,0,0,1,0,34 days 16:32:27
110524,1.557663e+13,5630692,F,2016-04-27 16:03:52,2016-06-07,21,MARIA ORTIZ,0,0,0,0,0,1,0,40 days 07:56:08
110525,9.213493e+13,5630323,F,2016-04-27 15:09:23,2016-06-07,38,MARIA ORTIZ,0,0,0,0,0,1,0,40 days 08:50:37
110526,3.775115e+14,5629448,F,2016-04-27 13:30:56,2016-06-07,54,MARIA ORTIZ,0,0,0,0,0,1,0,40 days 10:29:04

In [120]:
#changing sms_received data to boolean in order to extract row data
df_new['SMS_received'] = df_new['SMS_received'].astype(bool)
df_new.dtypes
df_new

,PatientId,AppointmentID,Gender,ScheduledDay,AppointmentDay,Age,Neighbourhood,Scholarship,Hipertension,Diabetes,Alcoholism,Handcap,SMS_received,Noshow,Daystoshow
0,2.987250e+13,5642903,F,2016-04-29 18:38:08,2016-04-29,62,JARDIM DA PENHA,0,1,0,0,0,False,0,-1 days +05:21:52
1,5.589978e+14,5642503,M,2016-04-29 16:08:27,2016-04-29,56,JARDIM DA PENHA,0,0,0,0,0,False,0,-1 days +07:51:33
2,4.262962e+12,5642549,F,2016-04-29 16:19:04,2016-04-29,62,MATA DA PRAIA,0,0,0,0,0,False,0,-1 days +07:40:56
3,8.679512e+11,5642828,F,2016-04-29 17:29:31,2016-04-29,8,PONTAL DE CAMBURI,0,0,0,0,0,False,0,-1 days +06:30:29
4,8.841186e+12,5642494,F,2016-04-29 16:07:23,2016-04-29,56,JARDIM DA PENHA,0,1,1,0,0,False,0,-1 days +07:52:37
5,9.598513e+13,5626772,F,2016-04-27 08:36:51,2016-04-29,76,REPÃšBLICA,0,1,0,0,0,False,0,1 days 15:23:09
6,7.336882e+14,5630279,F,2016-04-27 15:05:12,2016-04-29,23,GOIABEIRAS,0,0,0,0,0,False,1,1 days 08:54:48
7,3.449833e+12,5630575,F,2016-04-27 15:39:58,2016-04-29,39,GOIABEIRAS,0,0,0,0,0,False,1,1 days 08:20:02
8,5.639473e+13,5638447,F,2016-04-29 08:02:16,2016-04-29,21,ANDORINHAS,0,0,0,0,0,False,0,-1 days +15:57:44
9,7.812456e+13,5629123,F,2016-04-27 12:48:25,2016-04-29,19,CONQUISTA,0,0,0,0,0,False,0,1 days 11:11:35
10,7.345362e+14,5630213,F,2016-04-27 14:58:11,2016-04-29,30,NOVA PALESTINA,0,0,0,0,0,False,0,1 days 09:01:49
11,7.542951e+12,5620163,M,2016-04-26 08:44:12,2016-04-29,29,NOVA PALESTINA,0,0,0,0,0,True,1,2 days 15:15:48
12,5.666548e+14,5634718,F,2016-04-28 11:33:51,2016-04-29,22,NOVA PALESTINA,1,0,0,0,0,False,0,0 days 12:26:09
13,9.113946e+14,5636249,M,2016-04-28 14:52:07,2016-04-29,28,NOVA PALESTINA,0,0,0,0,0,False,0,0 days 09:07:53
14,9.988472e+13,5633951,F,2016-04-28 10:06:24,2016-04-29,54,NOVA PALESTINA,0,0,0,0,0,False,0,0 days 13:53:36
15,9.994839e+10,5620206,F,2016-04-26 08:47:27,2016-04-29,15,NOVA PALESTINA,0,0,0,0,0,True,0,2 days 15:12:33
16,8.457439e+13,5633121,M,2016-04-28 08:51:47,2016-04-29,50,NOVA PALESTINA,0,0,0,0,0,False,0,0 days 15:08:13
17,1.479497e+13,5633460,F,2016-04-28 09:28:57,2016-04-29,40,CONQUISTA,1,0,0,0,0,False,1,0 days 14:31:03
18,1.713538e+13,5621836,F,2016-04-26 10:54:18,2016-04-29,30,NOVA PALESTINA,1,0,0,0,0,True,0,2 days 13:05:42
19,7.223289e+12,5640433,F,2016-04-29 10:43:14,2016-04-29,46,DA PENHA,0,0,0,0,0,False,0,-1 days +13:16:46
20,6.222575e+14,5626083,F,2016-04-27 07:51:14,2016-04-29,30,NOVA PALESTINA,0,0,0,0,0,False,1,1 days 16:08:46
21,1.215484e+13,5628338,F,2016-04-27 10:50:45,2016-04-29,4,CONQUISTA,0,0,0,0,0,False,1,1 days 13:09:15
22,8.632298e+14,5616091,M,2016-04-25 13:29:16,2016-04-29,13,CONQUISTA,0,0,0,0,0,True,1,3 days 10:30:44
23,2.137540e+14,5634142,F,2016-04-28 10:27:05,2016-04-29,46,CONQUISTA,0,0,0,0,0,False,0,0 days 13:32:55
24,8.734858e+12,5641780,F,2016-04-29 14:19:19,2016-04-29,65,TABUAZEIRO,0,0,0,0,0,False,0,-1 days +09:40:41
25,5.819370e+12,5624020,M,2016-04-26 15:04:17,2016-04-29,46,CONQUISTA,0,1,0,0,0,True,0,2 days 08:55:43
26,2.578785e+10,5641781,F,2016-04-29 14:19:42,2016-04-29,45,BENTO FERREIRA,0,1,0,0,0,False,0,-1 days +09:40:18
27,1.215484e+13,5628345,F,2016-04-27 10:51:45,2016-04-29,4,CONQUISTA,0,0,0,0,0,False,0,1 days 13:08:15
28,5.926172e+12,5642400,M,2016-04-29 15:48:02,2016-04-29,51,SÃƒO PEDRO,0,0,0,0,0,False,0,-1 days +08:11:58
29,1.225776e+12,5642186,F,2016-04-29 15:16:29,2016-04-29,32,SANTA MARTHA,0,0,0,0,0,False,0,-1 days +08:43:31
...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...
110497,7.935892e+14,5757745,M,2016-06-01 09:46:33,2016-06-01,76,MARIA ORTIZ,0,0,0,0,0,False,0,-1 days +14:13:27
110498,9.433654e+13,5787655,F,2016-06-08 10:21:14,2016-06-08,59,MARIA ORTIZ,0,0,0,0,0,False,0,-1 days +13:38:46
110499,8.219692e+14,5757697,F,2016-06-01 09:42:56,2016-06-01,66,MARIA ORTIZ,0,1,1,0,0,False,0,-1 days +14:17:04
110500,4.434384e+14,5787233,F,2016-06-08 09:35:13,2016-06-08,59,MARIA ORTIZ,0,0,0,0,0,False,0,-1 days +14:24:47
110501,4.544252e+11,5758133,M,2016-06-01 10:19:12,2016-06-01,44,MARIA ORTIZ,0,0,0,0,0,False,0,-1 days +13:40:48
110502,7.316229e+14,5787937,F,2016-06-08 10:50:42,2016-06-08,22,GOIABEIRAS,0,0,0,0,0,False,0,-1 days +13:09:18
110503,2.362182e+13,5759473,F,2016-06-01 13:00:36,2016-06-01,64,SOLON BORGES,0,0,0,0,0,False,0,-1 days +10:59:24
110504,9.947983e+12,5788052,F,2016-06-08 11:06:21,2016-06-08,4,MARIA ORTIZ,0,0,0,0,0,False,0,-1 days +12:53:39
110505,5.667344e+13,5758455,F,2016-06-01 10:45:50,2016-06-01,55,MARIA ORTIZ,0,0,0,0,0,False,0,-1 days +13:14:10
110506,8.973883e+11,5758779,M,2016-06-01 11:09:20,2016-06-01,5,MARIA ORTIZ,0,0,0,0,0,False,0,-1 days +12:50:40
110507,4.769462e+14,5786918,F,2016-06-08 09:04:18,2016-06-08,0,MARIA ORTIZ,0,0,0,0,0,False,0,-1 days +14:55:42
110508,9.433654e+13,5757656,F,2016-06-01 09:41:00,2016-06-01,59,MARIA ORTIZ,0,0,0,0,0,False,0,-1 days +14:19:00
110509,4.952968e+14,5786750,M,2016-06-08 08:50:51,2016-06-08,33,MARIA ORTIZ,0,0,0,0,0,False,0,-1 days +15:09:09
110510,2.362182e+13,5757587,F,2016-06-01 09:35:48,2016-06-01,64,SOLON BORGES,0,0,0,0,0,False,0,-1 days +14:24:12
110511,8.235996e+11,5786742,F,2016-06-08 08:50:20,2016-06-08,14,MARIA ORTIZ,0,0,0,0,0,False,0,-1 days +15:09:40
110512,9.876246e+13,5786368,F,2016-06-08 08:20:01,2016-06-08,41,MARIA ORTIZ,0,0,0,0,0,False,0,-1 days +15:39:59
110513,8.674778e+13,5785964,M,2016-06-08 07:52:55,2016-06-08,2,ANTÃ”NIO HONÃ“RIO,0,0,0,0,0,False,0,-1 days +16:07:05
110514,2.695685e+12,5786567,F,2016-06-08 08:35:31,2016-06-08,58,MARIA ORTIZ,0,0,0,0,0,False,0,-1 days +15:24:29
110515,6.456342e+14,5778621,M,2016-06-06 15:58:05,2016-06-08,33,MARIA ORTIZ,0,1,0,0,0,False,1,1 days 08:01:55
110516,6.923772e+13,5780205,F,2016-06-07 07:45:16,2016-06-08,37,MARIA ORTIZ,0,0,0,0,0,False,1,0 days 16:14:44
110517,5.574942e+12,5780122,F,2016-06-07 07:38:34,2016-06-07,19,MARIA ORTIZ,0,0,0,0,0,False,0,-1 days +16:21:26
110518,7.263315e+13,5630375,F,2016-04-27 15:15:06,2016-06-07,50,MARIA ORTIZ,0,0,0,0,0,True,0,40 days 08:44:54
110519,6.542388e+13,5630447,F,2016-04-27 15:23:14,2016-06-07,22,MARIA ORTIZ,0,0,0,0,0,True,0,40 days 08:36:46
110520,9.969977e+14,5650534,F,2016-05-03 07:51:47,2016-06-07,42,MARIA ORTIZ,0,0,0,0,0,True,0,34 days 16:08:13
110521,3.635534e+13,5651072,F,2016-05-03 08:23:40,2016-06-07,53,MARIA ORTIZ,0,0,0,0,0,True,0,34 days 15:36:20
110522,2.572134e+12,5651768,F,2016-05-03 09:15:35,2016-06-07,56,MARIA ORTIZ,0,0,0,0,0,True,0,34 days 14:44:25
110523,3.596266e+12,5650093,F,2016-05-03 07:27:33,2016-06-07,51,MARIA ORTIZ,0,0,0,0,0,True,0,34 days 16:32:27
110524,1.557663e+13,5630692,F,2016-04-27 16:03:52,2016-06-07,21,MARIA ORTIZ,0,0,0,0,0,True,0,40 days 07:56:08
110525,9.213493e+13,5630323,F,2016-04-27 15:09:23,2016-06-07,38,MARIA ORTIZ,0,0,0,0,0,True,0,40 days 08:50:37
110526,3.775115e+14,5629448,F,2016-04-27 13:30:56,2016-06-07,54,MARIA ORTIZ,0,0,0,0,0,True,0,40 days 10:29:04

In [121]:
#trying to extract patients who are receiving SMS
#in addition, extracting patient who didn't and did show up
df_contains_sms_true = df_new.query('SMS_received == True')
df_contains_sms_true_noshow = df_contains_sms_true.query('Noshow == True')
df_contains_sms_true_show = df_new.query('Noshow == False')

In [122]:
#mean data of patients who received SMS and showed up
df_contains_sms_true_show.mean()

PatientId                   1.47685e+14
AppointmentID               5.68114e+06
Age                             37.7901
Scholarship                    0.093903
Hipertension                   0.204392
Diabetes                      0.0738368
Alcoholism                    0.0304167
Handcap                       0.0227417
SMS_received                   0.291334
Noshow                                0
Daystoshow       8 days 06:56:46.224594
dtype: object

In [123]:
#mean data of patients who received SMS but didn't showed up
df_contains_sms_true_noshow.mean()

PatientId                    1.45541e+14
AppointmentID                5.64267e+06
Age                               33.901
Scholarship                     0.121014
Hipertension                    0.157911
Diabetes                        0.055601
Alcoholism                     0.0283115
Handcap                        0.0150245
SMS_received                           1
Noshow                                 1
Daystoshow       19 days 12:25:48.932134
dtype: object

In [124]:
#trying to extract patients who are not receiving SMS
#in addition, extracting patient who didn't and did show up
df_contains_sms_false = df_new.query('SMS_received == False')
df_contains_sms_false_noshow = df_contains_sms_false.query('Noshow == True')
df_contains_sms_false_show = df_contains_sms_false.query('Noshow == False')

In [125]:
#mean data of patients who didn't receive SMS and not showed up
df_contains_sms_false_noshow.mean()

PatientId                    1.47697e+14
AppointmentID                5.65974e+06
Age                              34.6429
Scholarship                     0.111209
Hipertension                    0.177663
Diabetes                       0.0706821
Alcoholism                     0.0319107
Handcap                        0.0244116
SMS_received                           0
Noshow                                 1
Daystoshow       12 days 02:07:57.045712
dtype: object

In [126]:
#mean data of patients who didn't receive SMS and showed up
df_contains_sms_false_show.mean()

PatientId                   1.49517e+14
AppointmentID               5.69353e+06
Age                             37.3382
Scholarship                   0.0953767
Hipertension                   0.203231
Diabetes                       0.075204
Alcoholism                    0.0338026
Handcap                        0.025036
SMS_received                          0
Noshow                                0
Daystoshow       4 days 05:32:44.974708
dtype: object

In [127]:
#mean data of entire patients who didn't showed up
df_entire_noshow = df_new.query('Noshow == True')
df_entire_noshow.mean()

PatientId                    1.46752e+14
AppointmentID                5.65226e+06
Age                              34.3177
Scholarship                     0.115507
Hipertension                    0.169004
Diabetes                        0.064071
Alcoholism                     0.0303329
Handcap                        0.0202966
SMS_received                    0.438371
Noshow                                 1
Daystoshow       15 days 08:17:34.998879
dtype: object

In [128]:
#mean data of entire patients who showed up
df_entire_show = df_new.query('Noshow == False')
df_entire_show.mean()

PatientId                   1.47685e+14
AppointmentID               5.68114e+06
Age                             37.7901
Scholarship                    0.093903
Hipertension                   0.204392
Diabetes                      0.0738368
Alcoholism                    0.0304167
Handcap                       0.0227417
SMS_received                   0.291334
Noshow                                0
Daystoshow       8 days 06:56:46.224594
dtype: object